services:

  node_api:
    build:
      context: ./node-api
    ports:
      - "3000:3000"
    container_name: node_api
    volumes:
      - ./app_node:/app
    command: "node app.js"
    networks:
      - app-networks
    depends_on:
      - flask_api

  flask_api:
    build: ./python-api
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - "./python-api:/app"
    command: "python app.py"
    depends_on:
      - mysql_db
    networks:
      - app-networks

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge